Name: devhelp
Epoch: 1
Version: 3.30.0
Release: 1 
Summary: API documentation browser

License: GPLv2+
URL: https://wiki.gnome.org/Apps/Devhelp
Source0: https://download.gnome.org/sources/%{name}/3.30/%{name}-%{version}.tar.xz

BuildRequires: chrpath
BuildRequires: desktop-file-utils
BuildRequires: gettext
BuildRequires: gobject-introspection-devel
BuildRequires: gtk-doc
BuildRequires: itstool
BuildRequires: meson
BuildRequires: pkgconfig(amtk-5)
BuildRequires: pkgconfig(gsettings-desktop-schemas)
BuildRequires: pkgconfig(gtk+-3.0)
BuildRequires: pkgconfig(webkit2gtk-4.0)
BuildRequires: libappstream-glib

%description
Devhelp is an API documentation browser for the GNOME desktop.
It works natively with API documentation generated by gtk-doc.

%package libs
Summary: Library to embed Devhelp in other applications

%description libs
Devhelp is an API documentation browser for the GNOME desktop.
This package contains a library that can be used for embedding devhelp
into other applications such as IDEs.

%package devel
Summary: Library to embed Devhelp in other applications - Development files
Requires: %{name}%{?_isa} = %{epoch}:%{version}-%{release}

%description devel
Devhelp is an API documentation browser for the GNOME desktop.
This package contains the development files for the library that can be used
for embedding devhelp into other applications such as IDEs.

%prep
%setup -q

%build
%meson -Dgtk_doc=true
%meson_build

%install
%meson_install

mkdir -p $RPM_BUILD_ROOT%{_datadir}/devhelp/books

chrpath --delete $RPM_BUILD_ROOT%{_bindir}/devhelp

rm -rf ${RPM_BUILD_ROOT}%{_libdir}/gedit/plugins/__pycache__

%find_lang devhelp --with-gnome

%check
appstream-util validate-relax --nonet $RPM_BUILD_ROOT%{_datadir}/metainfo/org.gnome.Devhelp.appdata.xml
desktop-file-validate $RPM_BUILD_ROOT%{_datadir}/applications/org.gnome.Devhelp.desktop

%files
%doc AUTHORS NEWS README
%license COPYING

%{_bindir}/devhelp

%{_datadir}/applications/org.gnome.Devhelp.desktop
%{_datadir}/dbus-1/services/org.gnome.Devhelp.service
%{_datadir}/devhelp
%{_datadir}/glib-2.0/schemas/org.gnome.devhelp.gschema.xml
%{_datadir}/icons/hicolor/*/apps/org.gnome.Devhelp.png
%{_datadir}/icons/hicolor/symbolic/apps/org.gnome.Devhelp-symbolic.svg
%{_datadir}/metainfo/org.gnome.Devhelp.appdata.xml

%dir %{_libdir}/gedit
%dir %{_libdir}/gedit/plugins
%{_libdir}/gedit/plugins/devhelp.*

%files libs -f devhelp.lang
%{_libdir}/libdevhelp-3.so.6*
%{_libdir}/girepository-1.0/Devhelp-3.0.typelib
%{_datadir}/glib-2.0/schemas/org.gnome.libdevhelp-3.gschema.xml

%files devel
%{_includedir}/devhelp-3/
%{_libdir}/libdevhelp-3.so
%{_libdir}/pkgconfig/*
%{_datadir}/gtk-doc/*
%{_datadir}/gir-1.0/Devhelp-3.0.gir

%files help 
%{_mandir}/man1/devhelp.1*


%changelog
